---
- name: configure_root_access | updating root passwords
  community.mysql.mysql_user:
    host: "{{ item }}"
    login_unix_socket: "{{ mariadb_login_unix_socket | default(omit) }}"
    name: "root"
    password: "{{ mariadb_mysql_root_password }}"
  become: true
  no_log: "{{ galera_users_no_log | bool }}"
  ignore_errors: true
  run_once: true
  retries: 6
  delay: 5
  with_items:
    - "{{ ansible_hostname }}"
    - "127.0.0.1"
    - "::1"
    - "localhost"

- name: configure_root_access | configuring root my.cnf
  ansible.builtin.template:
    src: "root/my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: "root"
    group: "root"
    mode: "u=rw,g=,o="
  become: true
  no_log: "{{ galera_users_no_log | bool }}"

- name: configure_root_access | updating root passwords (allow from anywhere)
  community.mysql.mysql_user:
    host: "{{ item }}"
    login_unix_socket: "{{ mariadb_login_unix_socket | default(omit) }}"
    name: "root"
    password: "{{ mariadb_mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  become: true
  no_log: "{{ galera_users_no_log | bool }}"
  run_once: true
  retries: 6
  delay: 5
  with_items:
    - "%"
  when: galera_allow_root_from_any|bool
